data:
  target: "src.dataset.textdata.WrappedDataModule"
  batch_size: 16
  train:
    size: 256
    root_dir: "../dataset-stellar/STIPLAR-jp/train/"
    font_dir: "../dataset-stellar/STIPLAR-jp/fonts/"

  validation:
    size: 256
    root_dir: "../dataset-stellar/STIPLAR-jp/eval/"
    font_dir: "../dataset-stellar/STIPLAR-jp/fonts/"

stage:
  stage_type: 2
  model_path: "weights/model_stage1_jp.pth"
  learning_rate: 1e-5
  checkpoint_freq: 1

model:
  target: "src.trainer.CtrlBase.ControlBase"
  params:
    control_config:
      target: "src.trainer.CtrlBase.StylePyramidNet"
      params:
        image_size: 256
        patch_size: 16
        in_channels: 3
        embed_dim: 768
        model_channels: 320
        channel_mult: [ 1, 2, 4, 4 ]
        pyramid_sizes: [ 32, 16, 8, 4 ]


    base_config:
      noise_scheduler: "diffusers.PNDMScheduler"
      scheduler_config: "weights/sd/scheduler/scheduler_config.json"
      num_inference_steps: 50
      min_training_steps: 0

      vae:
        pretrained: "weights/sd/vae/"
        normalizer: 0.18215

      text_encoder_optimized: False
      text_encoder:
        target: "src.module.textencoder.modules.LanguageAdaptiveLabelEncoder"
        params:
          max_len: 12
          emb_dim: 768
          lang: "jp"
          character_path: "preglyph/data/character_jp.txt"
          ckpt_path: "weights/text_encoder_jp.pth"

      unet_pretrained: "weights/sd/unet/diffusion_pytorch_model.bin"
      unet:
        target: "src.trainer.CtrlBase.ControlUNetModel"
        params:
          cross_attention_dim: 768

      reconstruction_loss: True
      cond_on_text_image: False
      font_path: "datagen/fonts/jp_ttf/Kozuka_Gothic_Pro_R.ttf"

      ocr_model:
        lang: "jp"
        height: 48
        width: 320
        use_gpu: true
        max_length: 13
        iter_size: 3

      vgg_weight: "weights/vgg19.pth"

lightning:
  log_every_n_steps: 32
  accumulate_grad_batches: 8
  max_epochs: 10
  accelerator: "cuda"
  devices: [0, 1]
  strategy: ddp
  default_root_dir: "./logs/unet_logs"

image_logger:
  target: "src.trainer.Base.BaseImageLogger"
  params:
    train_batch_frequency: 2000
    valid_batch_frequency: 2
    disable_wandb: false
    generation_kwargs:
      num_inference_steps: 50
      num_sample_per_image: 1
      guidance_scale: 2
      seed: 42
